import { useState } from 'react';
import type { ProjectMeta, CalculatorInputs, CalculatorResults, CanvasComponent } from '../../types';
import ReportCover from './ReportCover';
import ReportSpecs from './ReportSpecs';
import ReportCost from './ReportCost';
import ReportLayout from './ReportLayout';
import { exportToPdf } from '../../utils/pdfExport';

interface Props {
  meta: ProjectMeta;
  inputs: CalculatorInputs;
  results: CalculatorResults;
  canvasItems: CanvasComponent[];
}

export default function ReportTab({ meta, inputs, results, canvasItems }: Props) {
  const [exporting, setExporting] = useState(false);

  async function handleExport() {
    setExporting(true);
    try {
      const filename = (meta.title || 'solar-proposal').replace(/\s+/g, '-').toLowerCase();
      await exportToPdf('report-root', filename);
    } finally {
      setExporting(false);
    }
  }

  return (
    <div className="flex flex-col h-full overflow-hidden">
      <div className="flex items-center justify-between px-6 py-3 bg-white border-b border-gray-200">
        <h2 className="text-sm font-semibold text-gray-700">Project Report Preview</h2>
        <button
          onClick={handleExport}
          disabled={exporting}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white text-sm font-medium px-4 py-2 rounded transition-colors"
        >
          {exporting ? (
            <>
              <span className="animate-spin">⏳</span> Generating PDF…
            </>
          ) : (
            <>
              📄 Download PDF
            </>
          )}
        </button>
      </div>

      <div className="flex-1 overflow-y-auto bg-gray-100 p-6">
        <div
          id="report-root"
          className="max-w-3xl mx-auto bg-white rounded-lg shadow p-8"
          style={{ fontFamily: 'Georgia, serif' }}
        >
          <ReportCover meta={meta} />
          <ReportSpecs inputs={inputs} results={results} />
          <ReportLayout items={canvasItems} />
          <ReportCost results={results} />

          <div className="mt-8 pt-4 border-t border-gray-200 text-xs text-gray-400 text-center">
            Generated by Solar Tool &nbsp;|&nbsp; Philippines Solar PV System Calculator
          </div>
        </div>
      </div>
    </div>
  );
}
